name: Reveal Secret

on: [push]

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reveal secret
        run: echo "The secret is: ${{ secrets.DUOLINGO_JWT }}"
